FROM arm64v8/alpine as gobuild
RUN apk update && apk add build-base pkgconfig go git libzmq zeromq-dev alpine-sdk libsodium-dev

ENV GOPATH /go
WORKDIR /
#COPY . . if you update the libs below build with --no-cache
RUN go get -u github.com/gorilla/mux
RUN go get -u github.com/gorilla/websocket
RUN go get -u github.com/pebbe/zmq4
RUN go get -u github.com/toshbrown/lib-go-databox
RUN go get -u github.com/me-box/goZestClient
RUN go get -u github.com/docker/docker/client
RUN go get -u github.com/docker/docker/api/types
RUN go get -u github.com/pkg/errors
RUN go get -u github.com/skip2/go-qrcode
RUN go get -u github.com/docker/go-connections
RUN rm -rf /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections
RUN go get -u github.com/toshbrown/lib-go-databox

COPY . /go/src/github.com/toshbrown/core-container-manager/
RUN addgroup -S databox && adduser -S -g databox databox
RUN GGO_ENABLED=0 GOOS=linux go build -a -tags netgo -installsuffix netgo -ldflags '-s -w' -o app /go/src/github.com/toshbrown/core-container-manager/*.go

FROM alpine
COPY --from=gobuild /etc/passwd /etc/passwd
RUN apk update && apk add libzmq
#TODO security
USER root
#TODO security
WORKDIR /
COPY --from=gobuild /app .
COPY --from=gobuild /go/src/github.com/toshbrown/core-container-manager/www /www
LABEL databox.type="container-manager"
EXPOSE 80 443
RUN rm -rf /certs/*
CMD ["./app"]
#CMD ["sleep","9999999"]